# cloudbuild.yaml
options:
  # stream logs only to Cloud Logging, don’t try to write to the default GCS bucket
 
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BACKEND_SERVICE: "car-rental-backend"
  _FRONTEND_SERVICE: "car-rental-frontend"
  _REGION: "asia-south1"

availableSecrets:
  secretManager:
  - versionName: "projects/$PROJECT_ID/secrets/SONARCLOUD_TOKEN/versions/latest"
    env: ["SONAR_TOKEN"]

steps:
  # 1) Install sonar-scanner
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "sonarqube-scanner"]

  # 2) Run SonarCloud analysis
  - name: "gcr.io/cloud-builders/sonarqube-scanner"
    entrypoint: "sonar-scanner"
    args: [
      "-Dsonar.login=${SONAR_TOKEN}"
    ]
    volumes:
      - name: "$HOME/.sonar/cache"
        path: "/root/.sonar/cache"
        
steps:
  # ── Build & Push Backend ─────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA',
        './Backend'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA'
      ]

  # ── Deploy Backend to Cloud Run ──────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_BACKEND_SERVICE}',
        '--image', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
          'MONGO_URI=mongodb+srv://ThimeshM:1234@cluster0.fclwnpx.mongodb.net/Cars?retryWrites=true&w=majority,JWT_SECRET=thisIsMySuperSecretKey'
      ]

  # ── Build & Push Frontend ────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg', 'REACT_APP_API_URL=https://$(gcloud run services describe car-rental-backend --region=${_REGION} --format="value(status.url)")/api',
        '-t', 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA',
        './frontend'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA'
      ]

  # ── Deploy Frontend to Cloud Run ─────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_FRONTEND_SERVICE}',
        '--image', 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA'
