version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

  backend:
    build:
      context: ./backend
    env_file: 
      - ./backend/.env       # contains MONGO_URI, JWT_SECRET, etc.
    depends_on:
      - mongo
    ports:
      - '5000:5000'
    # Override your MONGO_URI to point at the mongo service:
    environment:
      - MONGO_URI=mongodb://mongo:27017/Cars

  frontend:
    build:
      context: ./frontend
    ports:
      - '3001:80'
    depends_on:
      - backend
    # If you need to configure the API URL at runtime, you can:
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

volumes:
  mongo_data:
